esxi:
  hostname: "192.168.1.31"    # ESXiのIPアドレス
  username: "root"            # ESXiのログインユーザ
  password: "prompt:"         # ログインパスワード("prompt:" as manual ops)
  hostport: 22                # ESXiのsshログインポート

  virtualnetworks:            # どのネットワークに接続するかを指定
#   - "VLAN10"                # プライマリインタフェース
#   - "VM Network"            # 追加のネットワークインタフェース
  diskstore: "datastore1"     # 使用するデータストア名

baseos: "esxi_clone/dummy"    # 使用するOSイメージの指定
cloneos: "bento-centos-8"     # 使用するCloneイメージの指定
os_type: "centos-64"          # OSタイプ

#default-gw: "192.168.1.1"     # ネットワークのデフォルトゲートウェイの指定
#dns: "192.168.1.1"            # ネットワークのDNSサーバの指定

#guest_user: "vagrant"         # VMに作成するゲストユーザ名

nodes:
  - type: "control-plane"
    hostname: "k8s-master"
    cpus: 1
    memory: 2048
#   ip: "192.168.1.100"         # cluster作成用にcontrol-planeはIPを指定
    disk_type: "thin"
  - type: "worker"
    hostname: "k8s-node1"
    cpus: 1
    memory: 2048
    disk_type: "thin"
  - type: "worker"
    hostname: "k8s-node2"
    cpus: 1
    memory: 2048
    disk_type: "thin"

# - type: "control-plane"     # Control Plane or worker
#   hostname: "k8s-master"    # ホスト名かつ作成するVM名
#   cpus: 2                   # CPU数
#   memory: 4096              # メモリ(GB)
#   ip: "192.168.123.180"     # ノードのIPアドレス
#   disk_type: "thin"         # ディスクの形式（thin, thick, eagerzeroedthick）
#   disk_size: "200"          # ブートデバイスのディスクサイズ（GB） generic/centos8は128GB
