---
- name: configure jump server to control vagrant/ansible master
  hosts: jump_servers
  become: true
  user: vagrant
  vars_files:
    - inventories/common/vars/securities.yml
  vars:
    github_repo: 5laps2go

  tasks:
    - name: install EPEL
      package:
        name: epel-release
        state: present
    - name: set global LC_LOCALE to UTF-8
      lineinfile:
        path: /etc/environment
        line: 'LC_ALL=en_US.utf-8'
    - name: install packages
      package:
        name: python,git,gcc,wget,ansible,unzip
        state: present

    - name: setup vagrant yum repository
      get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: '0644'
    - name: install vagrant
      yum:
        name: vagrant
        state: present
    - name: install vagrant plugin vmware-esxi
      ansible.builtin.command: vagrant plugin install vagrant-vmware-esxi
      become: yes
      become_user: vagrant
      args:
        creates: /home/vagrant/.vagrant.d/gems/3.3.8/gems/vagrant-vmware-esxi-2.5.5

    - name: Unarchive VMware-ovftool
      unarchive:
        src:  VMware-ovftool-5.0.0-24781994-lin.x86_64.zip
        dest: /usr/lib
    - name: ovftool command
      ansible.builtin.file:
        src: /usr/lib/ovftool/ovftool
        dest: /usr/bin/ovftool
        state: link
    - name: install libnsl package for ovftool
      package:
        name: libnsl
        state: present

    - name: enable ssh forwarding
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - regexp: '^#?\s*AllowAgentForwarding'
          line: 'AllowAgentForwarding yes'
    - name: copy .ssh/config
      template:
        src: inventories/common/conf/ssh_config.j2
        dest: ~/.ssh/config
        mode: '0644'
      become: yes
      become_user: vagrant
    - name: add github ssh public key to vagrant user
      authorized_key:
        user: vagrant
        state: present
        key: https://github.com/{{ github_repo }}.keys
    - name: download ansible-galaxy role requirements
      copy:
        src: inventories/common/requirements.yml
        dest: /home/vagrant
        mode: '0644'
      become: yes
      become_user: vagrant
    - name: install the ansible roles
      command: ansible-galaxy install -r requirements.yml
      become: yes
      become_user: vagrant

    - name: prepare vagrant clone templates
      command: git clone git@github.com:5laps2go/vagrant-clone-templates.git
      args:
        creates: ./vagrant-clone-templates
      become: yes
      become_user: vagrant
    - name: prepare ESXIPASSWORD variable
      ansible.builtin.file:
        path: /home/vagrant/.bashrc.d
        state: directory
        owner: vagrant
        group: vagrant
    - name: .vault_pass file
      ansible.builtin.copy:
        src: inventories/dev/conf/esxipassword.sh
        dest: /home/vagrant/.bashrc.d/esxipassword.sh
        owner: vagrant
        group: vagrant
        follow: no
    - name: install vagrant dummy_box
      command: vagrant box add --name esxi_clone/dummy ~/vagrant-clone-templates/dummybox/dummy.box
      become: yes
      become_user: vagrant
      args:
        creates: /home/vagrant/vagrant-clone-templates/dummybox/dummy.box

#  roles:
#    - role: geerlingguy.repo-epel
#   - role: linux-system-roles.selinux
#   - role: linux-system-roles.firewall

# handlers:
#   - name: restart nginx
#     service: name=nginx state=restarted
