---
- name: install packages
  package:
    name: snapd
    state: present
- name: enable snapd.socket
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: yes
    state: started
- name: prepare snap environment
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
- name: snap install microk8s
  snap:
    name: microk8s
    classic: yes
    channel: 1.24/stable
    # 1.25 and 1.26 are not supported by centos7???
- name: adding existing user vagrant to group microk8s
  user:
    name: vagrant
    groups: microk8s
    append: yes
- name: alias kubectl
  command: snap alias microk8s.kubectl kubectl
- name: alias helm
  command: snap alias microk8s.helm3 helm
