# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Clone_from_templates test
#
require 'yaml'
settings = YAML.load_file('config.yml')

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  # preserve ssh insecure key for template preparation
  config.ssh.insert_key = false

  config.vm.define settings['node']['hostname'] do |node|
    node.vm.box = settings['vm']['baseos']

    node.vm.hostname = settings['node']['hostname']
    node.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)
    node.vm.synced_folder('.', '/vagrantfiles', type: 'rsync', disabled: true)
  
    node.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = settings['esxi']['hostname']
      esxi.esxi_username = settings['esxi']['username']
      esxi.esxi_password = ENV['ESXI_PASSWD']||settings['esxi']['password']
      esxi.esxi_hostport = settings['esxi']['hostport']
  
      esxi.esxi_disk_store = settings['vm']['diskstore']
      esxi.clone_from_vm = settings['vm']['cloneos']

      esxi.esxi_virtual_network = ["VM Network"]
      esxi.guest_memsize = settings['node']['memory']
      esxi.guest_numvcpus = settings['node']['cpus']
      esxi.guest_disk_type = settings['node']['disk_type']
      esxi.guest_boot_disk_size = settings['node']['disk_size']
      esxi.local_allow_overwrite = 'True'

      esxi.guest_custom_vmx_settings = [['pciPassthru0.present','TRUE'], ['pciPassthru0.pciSlotNumber','192'], ['pciPassthru0.id','00000:001:00.0'], ['pciPassthru0.deviceId','0x1f82'], ['pciPassthru0.vendorId','0x10de'], ['pciPassthru0.systemId','61d3b279-6cb1-ccff-5244-001517ddf3aa'], ['sched.mem.min','4096']]
# ['sched.mem.min','4096'], ['sched.mem.minSize',settings['node']['memory']], ['sched.mem.pin','TRUE'], ['sched.mem.shares','normal']
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "pycaret.yml"
    ansible.groups = {
      "pycaret_server" => [settings['node']['hostname']]
    }
  end
end

