---
- name: configure c9-rails server with nginx reverse proxy
  hosts: c9python_servers
  become: true
  user: vagrant
  vars_files:
    - inventories/dev/vars/c9servers.yml
  vars:
    python3_version: 3.8.13

  tasks:
    - import_tasks: ./tasks/nginx_htpasswd.yml
#   - name: install postgresql-devel for gem pg
#     package:
#       name: postgresql-devel
#       state: present
#   - name: git clone ixbrl-parse
#     git:
#       repo: https://github.com/drkane/ixbrl-parse.git
#       dest: ~/ixbrl-parse
#     become: yes
#     become_user: vagrant
    - name: install jupyter notebook systemd unit file
      template:
        src: inventories/common/conf/jupyter.service.j2
        dest: /etc/systemd/system/jupyter.service
    - name: ensures .jupyter dir exists
      file: path=/home/vagrant/.jupyter state=directory
      become: yes
      become_user: vagrant
    - name: set jupyter notebook customize json
      template:
        src: inventories/dev/conf/jupyter_server_config.json
        dest: /home/vagrant/.jupyter/jupyter_server_config.json
      become: yes
      become_user: vagrant

    - name: change python interpreter
      set_fact: ansible_python_interpreter=/home/vagrant/.pyenv/shims/python
    - name: upgrade pip, force upgrade
      pip:
        name: pip
        state: latest
      become: yes
      become_user: vagrant
    - name: install pycaret and jupyterlab
      pip:
        name: pycaret, jupyterlab, pandavro
        executable: pip3
      become: yes
      become_user: vagrant
    - name: start the jupyter service
      systemd:
        name: jupyter.service
        state: started
        daemon_reload: yes
        enabled: yes

  pre_tasks:
    - name: install packages for python
      package:
        name: xz-devel
        state: present

  roles:
#   - role: nginxinc.nginx
    - role: nginxinc.nginx_config
    - role: avanov.pyenv
      pyenv_path: /home/vagrant/.pyenv
      pyenv_owner: vagrant
      pyenv_global: "{{ python3_version }}"
      pyenv_python_versions: ["{{ python3_version }}"]
      pyenv_virtualenvs: [{ venv_name: "latest", py_version: "{{ python3_version }}" }]

